[Action]
Item=LEDTest_BMP
[Image]
Path=Utility\EO5002_IQ_LED\test_img\1_R.jpg
Address=0
Width=0
Height=0
Format=SE_BMP
[Parameters]
Method=1
OBValue=0
Binary_Threshold=10
Sample_BinaryTH_GChannel=200
Area_Threshold=2000
Merge_Distance=0
ShowDataNum=12
DebugMode=0
Search_Left_Pixel=0
Search_Top_Pixel=0
Search_Right_Pixel=1280
Search_Bottom_Pixel=1024
[Others]
ShowLog=0