[Action]
Item=IntensityCheck_BMP
[Image]
Path=Utility\EO5002_IQ_LED\test_img\1_W.jpg
Address=0
Width=0
Height=0
Format=SE_BMP
[Parameters]
Channel=3
ImageMode=-1
RAW_BayerPattern=1
Range_StartFromW=15000
Range_EndFromW=131072
Downsample=1
BMPTarget_Channel_BGRY=4
Search_Left_Pixel=0
Search_Top_Pixel=0
Search_Right_Pixel=1280
Search_Bottom_Pixel=1024
[Others]
ShowLog=0